import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'scandrive-language';
const translations = {
  fr: {
    brandTag: 'Marché auto QR',
    navHome: 'Accueil',
    navCars: 'Voitures',
    navAgencies: 'Agences',
    navLogin: 'Connexion',
    navRegister: 'Inscription',
    heroBadge: 'Frontend 100% mocké',
    heroTitle: 'ScanDrive réinvente la vente automobile en Tunisie autour du QR code et du mobile.',
    heroText: 'Parcours public, espace client, back-office vendeur et admin, le tout simulé localement avec des données de démo.',
    searchLabel: 'Recherche intelligente',
    searchPlaceholder: 'Ex: SUV hybride à Tunis, moins de 120000 TND',
    ctaStart: 'Commencer',
    ctaCatalogue: 'Voir le catalogue',
    landingFeatureTitle: 'Flux mobile-first pensé pour le scan en concession',
    landingFeatureSubtitle: 'Le client scanne un QR code sur la voiture, puis la fiche publique se charge instantanément.',
    heroLocation: 'En Tunisie',
    heroFeatureA: 'Scan instantané en concession',
    heroFeatureB: 'Données publiques riches',
    heroFeatureC: 'Rendez-vous simplifiés',
    heroFeatureD: 'Comparaison intelligente',
    trustedTitle: 'Conçu pour la route tunisienne',
    trustedText: 'Une expérience de showroom mobile-first qui transforme le scan QR en parcours client fluide.',
    scanSectionTitle: 'Scannez une voiture en agence',
    scanSectionSubtitle: 'En vrai showroom, le client scanne le QR code sur la voiture pour ouvrir sa fiche détaillée, tout en restant mobile et rapide.',
    scanNow: 'Scanner un QR de voiture',
    exploreCatalog: 'Voir l’inventaire agence',
    trustedAgencies: 'Agences partenaires',
    showroomFlowTitle: 'Flux showroom réel',
    showroomFlowStep1: 'Le visiteur arrive en agence et repère le QR collé sur le véhicule.',
    showroomFlowStep2: 'Un scan instantané ouvre la fiche publique de la voiture avec photos et specs.',
    showroomFlowStep3: 'Le client partage, ajoute aux favoris ou prend RDV avec l’agence.',
    showroomFlowCaption: 'Simulez le parcours d’un client qui scanne sur le stand, découvre la fiche et contacte le vendeur.',
    statsVehicles: 'voitures',
    statsAgencies: 'agences',
    statsScan: 'scan direct',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    language: 'Langue',
    modeDemo: 'Mode démo',
    logout: 'Déconnexion',
    saved: 'Sauvé',
    favorite: 'Favori',
    compare: 'Comparer',
    compared: 'Comparé',
    details: 'Détails',
    priceLabel: 'Prix',
    compareEmpty: 'Ajoutez des voitures au comparateur pour afficher le tableau.',
    compareCriteria: 'Critère',
    comparePrice: 'Prix',
    compareYear: 'Année',
    compareFuel: 'Carburant',
    compareTransmission: 'Boîte',
    compareCity: 'Ville',
    compareMileage: 'Kilométrage',
    compareStatus: 'Statut',
    chatbotTitle: 'ScanDrive Assistant',
    chatbotSubtitle: 'FAQ rapide et contexte de démo',
    faq1Question: 'Comment réserver un essai ?',
    faq1Answer: 'Ouvrez une fiche voiture, cliquez sur RDV et choisissez le type Essai routier.',
    faq2Question: 'Les QR codes marchent-ils ?',
    faq2Answer: 'Oui. Chaque voiture génère un QR code vers sa fiche publique.',
    faq3Question: 'Puis-je comparer des voitures ?',
    faq3Answer: 'Ajoutez jusqu’à 4 voitures au comparateur depuis la liste ou la fiche.',
    faq4Question: 'Les données sont-elles persistées ?',
    faq4Answer: 'Les favoris, la session et les RDV sont conservés en localStorage.',
    clientDashboardTitle: 'Tableau de bord client',
    favoritesTitle: 'Véhicules favoris et suggestions rapides',
    rdvTitle: 'Essai routier ou visite agence',
    compareTitle: 'Comparer jusqu’à 4 véhicules',
    appointmentsTitle: 'Prise de RDV',
    profileTitle: 'Historique simulé',
    messagesTitle: 'Conversations',
    replyTitle: 'Réponse rapide',
    adminCarsTitle: 'Gestion voitures',
    adminAgenciesTitle: 'Gestion agences',
    adminStatsTitle: 'Activité des voitures et rendez-vous',
    adminQrTitle: 'Générateur QR Code',
    menuDashboard: 'Tableau',
    menuFavorites: 'Favoris',
    menuCompare: 'Comparer',
    menuRdv: 'RDV',
    menuMessages: 'Messages',
    menuProfile: 'Profil',
    menuMyCars: 'Mes voitures',
    menuUsers: 'Utilisateurs',
    menuAgencies: 'Agences',
    menuStats: 'Stats',
    menuQr: 'QR',
  },
  en: {
    brandTag: 'QR Auto Market',
    navHome: 'Home',
    navCars: 'Cars',
    navAgencies: 'Agencies',
    navLogin: 'Login',
    navRegister: 'Sign up',
    heroBadge: '100% mocked frontend',
    heroTitle: 'ScanDrive reinvents car sales in Tunisia around QR codes and mobile-first browsing.',
    heroText: 'Public browsing, client space, seller and admin back office, all simulated locally with demo data.',
    searchLabel: 'Smart search',
    searchPlaceholder: 'Ex: hybrid SUV in Tunis, under 120000 TND',
    ctaStart: 'Get started',
    ctaCatalogue: 'Browse catalog',
    landingFeatureTitle: 'Mobile-first flow designed for showroom QR scans',
    landingFeatureSubtitle: 'A customer scans a QR code on the car, and the public detail page opens instantly.',
    heroLocation: 'In Tunisia',
    heroFeatureA: 'Instant showroom scan',
    heroFeatureB: 'Rich public listing data',
    heroFeatureC: 'Simplified appointment flow',
    heroFeatureD: 'Smart vehicle comparison',
    trustedTitle: 'Built for Tunisia’s showroom future',
    trustedText: 'A mobile-first QR experience that turns scanning into a seamless buyer journey.',
    scanSectionTitle: 'Scan a vehicle at the showroom',
    scanSectionSubtitle: 'In a real showroom, a visitor scans the QR on the car to open the detailed listing instantly.',
    scanNow: 'Scan a car QR',
    exploreCatalog: 'View agency inventory',
    trustedAgencies: 'Partner agencies',
    showroomFlowTitle: 'Real showroom flow',
    showroomFlowStep1: 'A visitor finds the QR code attached to a car in the showroom.',
    showroomFlowStep2: 'Scanning immediately opens the public detail page with photos and specs.',
    showroomFlowStep3: 'They save favorites, compare options, or schedule a visit with the agency.',
    showroomFlowCaption: 'Simulate a buyer scanning on the lot, browsing the car, and contacting the seller.',
    statsVehicles: 'vehicles',
    statsAgencies: 'agencies',
    statsScan: 'instant scan',
    themeLight: 'Light',
    themeDark: 'Dark',
    language: 'Language',
    modeDemo: 'Demo mode',
    logout: 'Logout',
    saved: 'Saved',
    favorite: 'Favorite',
    compare: 'Compare',
    compared: 'Compared',
    details: 'Details',
    priceLabel: 'Price',
    compareEmpty: 'Add cars to the comparison table to view them side by side.',
    compareCriteria: 'Criteria',
    comparePrice: 'Price',
    compareYear: 'Year',
    compareFuel: 'Fuel',
    compareTransmission: 'Transmission',
    compareCity: 'City',
    compareMileage: 'Mileage',
    compareStatus: 'Status',
    chatbotTitle: 'ScanDrive Assistant',
    chatbotSubtitle: 'Quick FAQ and demo context',
    faq1Question: 'How do I book a test drive?',
    faq1Answer: 'Open a car detail page, click RDV, and choose the test drive type.',
    faq2Question: 'Do the QR codes work?',
    faq2Answer: 'Yes. Each car generates a QR code linking to its public detail page.',
    faq3Question: 'Can I compare cars?',
    faq3Answer: 'Add up to 4 cars to the compare section from the list or detail page.',
    faq4Question: 'Is the data persisted?',
    faq4Answer: 'Favorites, session, and appointments are saved in localStorage.',
    clientDashboardTitle: 'Client dashboard',
    favoritesTitle: 'Favorite cars and quick suggestions',
    rdvTitle: 'Test drive or agency visit',
    compareTitle: 'Compare up to 4 cars',
    appointmentsTitle: 'Appointment booking',
    profileTitle: 'Simulated history',
    messagesTitle: 'Conversations',
    replyTitle: 'Quick reply',
    adminCarsTitle: 'Car management',
    adminAgenciesTitle: 'Agency management',
    adminStatsTitle: 'Car and appointment activity',
    adminQrTitle: 'QR code generator',
    menuDashboard: 'Dashboard',
    menuFavorites: 'Favorites',
    menuCompare: 'Compare',
    menuRdv: 'Appointments',
    menuMessages: 'Messages',
    menuProfile: 'Profile',
    menuMyCars: 'My cars',
    menuUsers: 'Users',
    menuAgencies: 'Agencies',
    menuStats: 'Stats',
    menuQr: 'QR',
  },
  ar: {
    brandTag: 'سوق السيارات QR',
    navHome: 'الرئيسية',
    navCars: 'السيارات',
    navAgencies: 'الوكالات',
    navLogin: 'تسجيل الدخول',
    navRegister: 'إنشاء حساب',
    heroBadge: 'واجهة أمامية تجريبية بالكامل',
    heroTitle: 'ScanDrive يعيد ابتكار بيع السيارات في تونس عبر رمز QR وتجربة موجهة للهاتف.',
    heroText: 'تصفح عام، مساحة للعميل، ولوحات للبائع والمدير، كلها محاكاة محلية ببيانات تجريبية.',
    searchLabel: 'بحث ذكي',
    searchPlaceholder: 'مثال: سيارة SUV هجينة في تونس، أقل من 120000 دينار',
    ctaStart: 'ابدأ الآن',
    ctaCatalogue: 'عرض الكتالوج',
    landingFeatureTitle: 'تجربة موجهة للهاتف لمسح QR في المعرض',
    landingFeatureSubtitle: 'يمسح العميل رمز QR على السيارة فتفتح صفحة التفاصيل العامة مباشرة.',
    heroLocation: 'في تونس',
    heroFeatureA: 'مسح فوري داخل المعرض',
    heroFeatureB: 'بيانات عرض عامة غنية',
    heroFeatureC: 'حجز مواعيد مبسط',
    heroFeatureD: 'مقارنة ذكية للسيارات',
    trustedTitle: 'مصمم لمستقبل العرض التونسي',
    trustedText: 'تجربة QR موجهة للهاتف تحوّل المسح إلى رحلة شراء سلسة.',
    scanSectionTitle: 'امسح سيارة في صالة العرض',
    scanSectionSubtitle: 'في صالة عرض حقيقية، يمسح الزائر رمز QR على السيارة لفتح صفحتها التفصيلية فوراً.',
    scanNow: 'امسح رمز QR للسيارة',
    exploreCatalog: 'عرض مخزون الوكالة',
    trustedAgencies: 'الوكالات الشريكة',
    showroomFlowTitle: 'تجربة صالة عرض حقيقية',
    showroomFlowStep1: 'يجد الزائر رمز QR الملصق على السيارة في صالة العرض.',
    showroomFlowStep2: 'المسح يفتح فوراً صفحة السيارة العامة مع الصور والمواصفات.',
    showroomFlowStep3: 'يضيفها إلى المفضلات أو يقارنها أو يحدد موعدًا مع الوكالة.',
    showroomFlowCaption: 'حاكي رحلة المشتري من المسح على الأرض إلى استعراض السيارة والتواصل مع البائع.',
    statsVehicles: 'سيارات',
    statsAgencies: 'وكالات',
    statsScan: 'مسح مباشر',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    language: 'اللغة',
    modeDemo: 'وضع تجريبي',
    logout: 'تسجيل الخروج',
    saved: 'تم الحفظ',
    favorite: 'مفضل',
    compare: 'مقارنة',
    compared: 'تمت المقارنة',
    details: 'تفاصيل',
    priceLabel: 'السعر',
    compareEmpty: 'أضف سيارات إلى المقارنة لعرض الجدول.',
    compareCriteria: 'المعيار',
    comparePrice: 'السعر',
    compareYear: 'السنة',
    compareFuel: 'الوقود',
    compareTransmission: 'ناقل الحركة',
    compareCity: 'المدينة',
    compareMileage: 'المسافة',
    compareStatus: 'الحالة',
    chatbotTitle: 'مساعد ScanDrive',
    chatbotSubtitle: 'الأسئلة الشائعة وسياق العرض التجريبي',
    faq1Question: 'كيف أحجز اختبار قيادة؟',
    faq1Answer: 'افتح صفحة السيارة، انقر على RDV، واختر نوع الاختبار.',
    faq2Question: 'هل تعمل رموز QR؟',
    faq2Answer: 'نعم. كل سيارة تولد رمز QR يربط بصفحتها العامة.',
    faq3Question: 'هل يمكنني مقارنة السيارات؟',
    faq3Answer: 'أضف حتى 4 سيارات إلى قسم المقارنة من القائمة أو الصفحة.',
    faq4Question: 'هل يتم حفظ البيانات؟',
    faq4Answer: 'يتم حفظ المفضلات والجلسة والمواعيد في localStorage.',
    clientDashboardTitle: 'لوحة العميل',
    favoritesTitle: 'السيارات المفضلة والاقتراحات السريعة',
    rdvTitle: 'اختبار قيادة أو زيارة وكالة',
    compareTitle: 'مقارنة حتى 4 سيارات',
    appointmentsTitle: 'حجز موعد',
    profileTitle: 'السجل المحلي التجريبي',
    messagesTitle: 'المحادثات',
    replyTitle: 'رد سريع',
    adminCarsTitle: 'إدارة السيارات',
    adminAgenciesTitle: 'إدارة الوكالات',
    adminStatsTitle: 'نشاط السيارات والمواعيد',
    adminQrTitle: 'مولد رمز QR',
    menuDashboard: 'لوحة',
    menuFavorites: 'المفضلة',
    menuCompare: 'المقارنة',
    menuRdv: 'المواعيد',
    menuMessages: 'الرسائل',
    menuProfile: 'الملف',
    menuMyCars: 'سياراتي',
    menuUsers: 'المستخدمين',
    menuAgencies: 'الوكالات',
    menuStats: 'الإحصائيات',
    menuQr: 'QR',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => window.localStorage.getItem(STORAGE_KEY) || 'fr');

  useEffect(() => {
    const root = document.documentElement;
    root.lang = language;
    root.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage: (nextLanguage) => {
      setLanguage(nextLanguage);
      window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    },
    t: translations[language] || translations.fr,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}